name: flutter_helper
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # 国际化
    sdk: flutter
  intl: ^0.17.0 # 国际化语言
  # https://github.com/a14n/dart-decimal
  decimal: ">=1.0.0 <3.0.0"
  # https://github.com/dart-lang/crypto
  crypto: ">=3.0.0 <5.0.0"
  # https://github.com/dart-lang/convert
  convert: ">=3.0.0 <5.0.0"
  fluttertoast: ^4.0.1
  flutter_webview_plugin: ^0.3.5
  http: ^0.13.1
  syntax_highlighter: ^0.1.1 # 语法高亮
  underline_indicator: ^0.0.2
  flutter_staggered_grid_view: ^0.3.0
  flutter_swiper: ^1.1.4
  audioplayers: ^0.19.0
  path_provider: ^2.0.1
  flutter_keyboard_visibility: ^5.0.0
  google_fonts: ^2.0.0
  rect_getter: ^1.0.0
  cached_network_image: ^3.0.0
  spring_button: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  image: ^3.0.2
  flutter_colorpicker: ^0.4.0
  flutter_highlight: ^0.7.0
  url_launcher: ^6.0.7
  url_launcher_web: ^2.0.1
  provider: ^5.0.0
  flip_card: ^0.5.0
  dotted_border: ^1.0.4
  flutter_sequence_animation: ^3.0.1
  sensors: ^2.0.0
  equatable: ^2.0.0
  vector_math: ^2.1.0

  extended_masked_text: ^2.1.0
  meta: ^1.2.4
  flutter_cupertino_settings: ^0.5.0
  flutter_material_pickers: ^3.0.0
  pattern_formatter: ^2.0.0 # used for localized doubles
  flutter_multi_formatter: ^2.0.2 # used for localized phone numbers
  adaptive_theme: ^2.0.0
  # google_fonts: ^2.0.0
  font_awesome_flutter: ^9.0.0
  simple_gesture_detector: ^0.2.0
  timezone: ^0.7.0-nullsafety.0
  clock: ^1.1.0
  flutter_native_timezone: ^1.0.4
  connectivity: ^3.0.2
  wifi_info_flutter: ^2.0.0
  cupertino_icons: ^1.0.0
  flutter_offline: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  very_good_analysis: ^2.0.0
  test:
  mockito: ^5.0.2
  pedantic: ^1.11.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true # 国际化语言
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

    - sounds/box_down.mp3
    - sounds/box_up.mp3
    - sounds/icon_choose.mp3
    - sounds/icon_focus.mp3
    - sounds/short_press_like.mp3

    - readme_resources/

    - img/
    - img/bg/
    - img/source/gift.ai
    - res/portrait.jpeg

    - assets/
    - assets/images/
    - assets/timezone/2018c.tzf



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-ExtraBold.ttf
          weight: 800
    - family: U and I
      fonts:
        - asset: fonts/fontYouandiModernTR.ttf
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
    - family: NeumorphicIcons
      fonts:
        - asset: fonts/NeumorphicIcons.ttf
    - family: Samsung
      fonts:
        - asset: fonts/SamsungSans-Bold.ttf
    - family: Themify
      fonts:
        - asset: assets/fonts/themify.ttf
    - family: LineAwesome
      fonts:
        - asset: assets/fonts/line-awesome.ttf
    - family: Timeburner
      fonts:
        - asset: assets/fonts/timeburnernormal.ttf
        - asset: assets/fonts/timeburnerbold.ttf
          weight: 700

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
