{
  "formatVersion": "1.1",
  "component": {
    "group": "com.joyy.router",
    "module": "router-annotations",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "router-annotations-2.0.1.jar",
          "url": "router-annotations-2.0.1.jar",
          "size": 1129,
          "sha512": "4237fe941c34bc703b996e5c12e434c927181bff62fd6383eec0b67606beb06b8cd2522e63dd91c572f345baa631a4f535951288d2e54bd4a2d633d9c5cb4ec1",
          "sha256": "9046357ae437a96271ada860ad75185da2e55f87fdd525389adfa537f62e7757",
          "sha1": "08cd0fe9f0593f054684b05d207b78ebc76df564",
          "md5": "3f01299c95d173d9a74215565b10a363"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "router-annotations-2.0.1.jar",
          "url": "router-annotations-2.0.1.jar",
          "size": 1129,
          "sha512": "4237fe941c34bc703b996e5c12e434c927181bff62fd6383eec0b67606beb06b8cd2522e63dd91c572f345baa631a4f535951288d2e54bd4a2d633d9c5cb4ec1",
          "sha256": "9046357ae437a96271ada860ad75185da2e55f87fdd525389adfa537f62e7757",
          "sha1": "08cd0fe9f0593f054684b05d207b78ebc76df564",
          "md5": "3f01299c95d173d9a74215565b10a363"
        }
      ]
    }
  ]
}
