{
  "formatVersion": "1.1",
  "component": {
    "group": "com.joyy.router",
    "module": "router-annotations",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "router-annotations-1.0.0.jar",
          "url": "router-annotations-1.0.0.jar",
          "size": 1129,
          "sha512": "0bcd6bf589c01ccc01c7e0628fcdd961a57731e4bd712dcbc9427a4c93b68924b9486ebbefbf658fb7727660861733013c2b5cfac00d145c17cfe4ef1a5dcc93",
          "sha256": "9d934cbe6dd320445de13995f3449f7c1f4e7fd785db0faa00c1379b94e2748f",
          "sha1": "6f93f97ccc04b60682623e7321644239dd668d0b",
          "md5": "5984f460cf061f829998cb0d1cb6aae9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "router-annotations-1.0.0.jar",
          "url": "router-annotations-1.0.0.jar",
          "size": 1129,
          "sha512": "0bcd6bf589c01ccc01c7e0628fcdd961a57731e4bd712dcbc9427a4c93b68924b9486ebbefbf658fb7727660861733013c2b5cfac00d145c17cfe4ef1a5dcc93",
          "sha256": "9d934cbe6dd320445de13995f3449f7c1f4e7fd785db0faa00c1379b94e2748f",
          "sha1": "6f93f97ccc04b60682623e7321644239dd668d0b",
          "md5": "5984f460cf061f829998cb0d1cb6aae9"
        }
      ]
    }
  ]
}
